-- Seed unificado de productos básicos para FreshKeeper
-- Productos que se compran a granel (sin código de barras)
-- Combina lo mejor de ambos archivos: completo + correcto

-- FRUTAS (13 productos)
INSERT INTO products (
    id, barcode, name, name_translations, brand, brand_translations,
    category, category_translations, subcategory, description,
    description_translations, image_url, nutritional_info, allergens,
    ingredients, ingredients_translations, source, source_id, is_verified,
    created_by_id, created_at, updated_at
) VALUES 
-- Frutas básicas
('03b5578f-380d-4a63-83fd-97bd3901b242', NULL, 'Manzana',
    '{"es":"Manzana","en":"Apple","fr":"Pomme"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Manzana',
    '{"es":"Manzana","en":"Apple","fr":"Pomme"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('a3926df0-5029-4d25-b66e-242b74baf521', NULL, 'Plátano',
    '{"es":"Plátano","en":"Banana","fr":"Banane"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Plátano',
    '{"es":"Plátano","en":"Banana","fr":"Banane"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('ffea2590-6937-4398-9926-24b0725c1d2c', NULL, 'Naranja',
    '{"es":"Naranja","en":"Orange","fr":"Orange"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Naranja',
    '{"es":"Naranja","en":"Orange","fr":"Orange"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('1ab9cf65-ad35-49cc-b98f-4de8514e2128', NULL, 'Pera',
    '{"es":"Pera","en":"Pear","fr":"Poire"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pera',
    '{"es":"Pera","en":"Pear","fr":"Poire"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('2215b76c-70e7-46cc-b4e8-4693efb478f4', NULL, 'Fresa',
    '{"es":"Fresa","en":"Strawberry","fr":"Fraise"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Fresa',
    '{"es":"Fresa","en":"Strawberry","fr":"Fraise"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('b619cb5a-cd1f-4ca9-9541-0dbceafe2ef1', NULL, 'Mandarina',
    '{"es":"Mandarina","en":"Mandarin","fr":"Mandarine"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Mandarina',
    '{"es":"Mandarina","en":"Mandarin","fr":"Mandarine"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('ad9ad61a-2677-4b71-baca-e189289fa663', NULL, 'Uva',
    '{"es":"Uva","en":"Grape","fr":"Raisin"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Uva',
    '{"es":"Uva","en":"Grape","fr":"Raisin"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('982a5f0d-23c1-4ab8-9227-5f29ec93795f', NULL, 'Sandía',
    '{"es":"Sandía","en":"Watermelon","fr":"Pastèque"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Sandía',
    '{"es":"Sandía","en":"Watermelon","fr":"Pastèque"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('52d0c180-6ce4-471c-8f9c-2c54c2334337', NULL, 'Melón',
    '{"es":"Melón","en":"Melon","fr":"Melon"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Melón',
    '{"es":"Melón","en":"Melon","fr":"Melon"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('642bf869-96f1-436c-bfcb-9779c1e88332', NULL, 'Kiwi',
    '{"es":"Kiwi","en":"Kiwi","fr":"Kiwi"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Kiwi',
    '{"es":"Kiwi","en":"Kiwi","fr":"Kiwi"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('ec80b9c9-e5ee-4ba3-be5d-8d623354f0c4', NULL, 'Piña',
    '{"es":"Piña","en":"Pineapple","fr":"Ananas"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Piña',
    '{"es":"Piña","en":"Pineapple","fr":"Ananas"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('cd4e0e0c-b4e7-45fa-ab73-c0ebe67f0fc2', NULL, 'Mango',
    '{"es":"Mango","en":"Mango","fr":"Mangue"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'fruits', '{"es":"Frutas","en":"Fruits","fr":"Fruits"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Mango',
    '{"es":"Mango","en":"Mango","fr":"Mangue"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

-- VERDURAS (12 productos)
('d0957a64-0f8d-4592-a04b-2ab7e3a11850', NULL, 'Tomate',
    '{"es":"Tomate","en":"Tomato","fr":"Tomate"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Tomate',
    '{"es":"Tomate","en":"Tomato","fr":"Tomate"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('32e4cc18-9625-4008-ba7f-c3e340a67ae3', NULL, 'Lechuga',
    '{"es":"Lechuga","en":"Lettuce","fr":"Laitue"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Lechuga',
    '{"es":"Lechuga","en":"Lettuce","fr":"Laitue"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('b54a81e1-c870-4eee-9804-a0406e020eb6', NULL, 'Cebolla',
    '{"es":"Cebolla","en":"Onion","fr":"Oignon"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Cebolla',
    '{"es":"Cebolla","en":"Onion","fr":"Oignon"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('13bbdb85-aeec-412a-9deb-869988322e58', NULL, 'Ajo',
    '{"es":"Ajo","en":"Garlic","fr":"Ail"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Ajo',
    '{"es":"Ajo","en":"Garlic","fr":"Ail"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('9157cc44-878d-48fb-a4cd-3c3717dedcbc', NULL, 'Zanahoria',
    '{"es":"Zanahoria","en":"Carrot","fr":"Carotte"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Zanahoria',
    '{"es":"Zanahoria","en":"Carrot","fr":"Carotte"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()), 

('7a6c798d-5771-4bbd-a7a4-47e08271ac6a', NULL, 'Pepino',
    '{"es":"Pepino","en":"Cucumber","fr":"Concombre"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pepino',
    '{"es":"Pepino","en":"Cucumber","fr":"Concombre"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('be969b6c-5d22-488a-a635-ef41511dcf95', NULL, 'Pimiento rojo',
    '{"es":"Pimiento rojo","en":"Red pepper","fr":"Poivron rouge"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pimiento rojo',
    '{"es":"Pimiento rojo","en":"Red pepper","fr":"Poivron rouge"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('1248c01b-7d9c-4644-9c39-b10c86deb1bf', NULL, 'Pimiento verde',
    '{"es":"Pimiento verde","en":"Green pepper","fr":"Poivron vert"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pimiento verde',
    '{"es":"Pimiento verde","en":"Green pepper","fr":"Poivron vert"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('71ac9edf-6398-4f8b-a47c-85a4cbb93d93', NULL, 'Calabacín',
    '{"es":"Calabacín","en":"Zucchini","fr":"Courgette"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Calabacín',
    '{"es":"Calabacín","en":"Zucchini","fr":"Courgette"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('206e082e-cae1-4acd-b1ad-ad1267ec2744', NULL, 'Berenjena',
    '{"es":"Berenjena","en":"Eggplant","fr":"Aubergine"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Berenjena',
    '{"es":"Berenjena","en":"Eggplant","fr":"Aubergine"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('8825b667-96b4-4210-ae18-89fff82d4d1d', NULL, 'Patata',
    '{"es":"Patata","en":"Potato","fr":"Pomme de terre"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Patata',
    '{"es":"Patata","en":"Potato","fr":"Pomme de terre"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('0cd239a2-ca48-47ee-942c-431853692667', NULL, 'Brócoli',
    '{"es":"Brócoli","en":"Broccoli","fr":"Brocoli"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'vegetables', '{"es":"Verduras","en":"Vegetables","fr":"Légumes"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Brócoli',
    '{"es":"Brócoli","en":"Broccoli","fr":"Brocoli"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

-- LÁCTEOS (3 productos)
('550e8400-e29b-41d4-a716-446655440011', NULL, 'Leche Fresca',
    '{"es":"Leche Fresca","en":"Fresh Milk","fr":"Lait Frais"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'dairy', '{"es":"Lácteos","en":"Dairy","fr":"Produits Laitiers"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Leche Fresca',
    '{"es":"Leche Fresca","en":"Fresh Milk","fr":"Lait Frais"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440012', NULL, 'Queso Fresco',
    '{"es":"Queso Fresco","en":"Fresh Cheese","fr":"Fromage Frais"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'dairy', '{"es":"Lácteos","en":"Dairy","fr":"Produits Laitiers"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Queso Fresco',
    '{"es":"Queso Fresco","en":"Fresh Cheese","fr":"Fromage Frais"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440013', NULL, 'Yogur Natural',
    '{"es":"Yogur Natural","en":"Natural Yogurt","fr":"Yaourt Nature"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'dairy', '{"es":"Lácteos","en":"Dairy","fr":"Produits Laitiers"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Yogur Natural',
    '{"es":"Yogur Natural","en":"Natural Yogurt","fr":"Yaourt Nature"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

-- CARNE (3 productos)
('550e8400-e29b-41d4-a716-446655440014', NULL, 'Pollo',
    '{"es":"Pollo","en":"Chicken","fr":"Poulet"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'meat', '{"es":"Carne","en":"Meat","fr":"Viande"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pollo',
    '{"es":"Pollo","en":"Chicken","fr":"Poulet"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440015', NULL, 'Ternera',
    '{"es":"Ternera","en":"Beef","fr":"Bœuf"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'meat', '{"es":"Carne","en":"Meat","fr":"Viande"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Ternera',
    '{"es":"Ternera","en":"Beef","fr":"Bœuf"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440016', NULL, 'Cerdo',
    '{"es":"Cerdo","en":"Pork","fr":"Porc"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'meat', '{"es":"Carne","en":"Meat","fr":"Viande"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Cerdo',
    '{"es":"Cerdo","en":"Pork","fr":"Porc"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

-- GRANOS (4 productos)
('550e8400-e29b-41d4-a716-446655440017', NULL, 'Arroz',
    '{"es":"Arroz","en":"Rice","fr":"Riz"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'grains', '{"es":"Granos","en":"Grains","fr":"Céréales"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Arroz',
    '{"es":"Arroz","en":"Rice","fr":"Riz"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440018', NULL, 'Pasta',
    '{"es":"Pasta","en":"Pasta","fr":"Pâtes"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'grains', '{"es":"Granos","en":"Grains","fr":"Céréales"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pasta',
    '{"es":"Pasta","en":"Pasta","fr":"Pâtes"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440019', NULL, 'Pan',
    '{"es":"Pan","en":"Bread","fr":"Pain"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'grains', '{"es":"Granos","en":"Grains","fr":"Céréales"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Pan',
    '{"es":"Pan","en":"Bread","fr":"Pain"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW()),

('550e8400-e29b-41d4-a716-446655440020', NULL, 'Avena',
    '{"es":"Avena","en":"Oats","fr":"Avoine"}',
    NULL, '{"es":null,"en":null,"fr":null}',
    'grains', '{"es":"Granos","en":"Grains","fr":"Céréales"}',
    NULL, 'Producto básico',
    '{"es":"Producto básico","en":"Basic product","fr":"Produit de base"}',
    NULL, '{}', ARRAY[]::text[], 'Avena',
    '{"es":"Avena","en":"Oats","fr":"Avoine"}',
    'manual', NULL, TRUE, NULL, NOW(), NOW());

-- Resumen: 35 productos básicos
-- 12 Frutas + 12 Verduras + 3 Lácteos + 3 Carnes + 4 Granos = 34 productos
